version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: task_system
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task-network
    restart: unless-stopped

  api:
    build: .
    container_name: task-api
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_system?createDatabaseIfNotExists=true
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass
    depends_on:
      - mysql
    networks:
      - task-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  task-network:
    driver: bridge
